### ISSUE TITLE
Add a way to configurate login_url and logout_url

### ISSUE THREAD

**Issue by valych** [cuducos/flask_simplelogin#6]
Hola! Thanks for the app, it's really cool, simple and time-saving.   
   
   
I had a need to change some in-app variables (login_url, logout_url and home_url) and found it difficult because a method like this
```
sl = SimpleLogin(app)
sl.config['login_url'] = '/admin/login/'
sl.config['logout_url'] = '/admin/logout/'
sl.config['home_url'] = '/admin/'
```

isn't working (views for login and logout are already registered at `__init__`) and changing blueprint url rules after that is a bit too hard.

It would be great to have an ability to set this urls by writing something like this
```
SIMPLELOGIN_LOGIN_URL = '/admin/login/'
SIMPLELOGIN_LOGOUT_URL = '/admin/logout/'
SIMPLELOGIN_HOME_URL = '/admin/'
```
or this
`SimpleLogin(app, login_url='/admin/login/', logout_url='/admin/logout/', 'home_url'='/admin/')`   
   
   
I could try to send a pull request, but not sure what method (or both) is better.

**Comment by rochacbruno** [comment]
Currently all `app.config` variables prefixed with `SIMPLE_LOGIN_` are loaded here (before the views are registered)

https://github.com/rochacbruno/flask_simplelogin/blob/master/flask_simplelogin/__init__.py#L201

So, `app.config['SIMPLE_LOGIN_HOME_URL']` will become `sl.config['home_url']`

and the same for `login_url` and `logout_url`

However now I see that we are inconsistency using `SIMPLELOGIN` and `SIMPLE_LOGIN` I would prefer to use only `SIMPLELOGIN` without the underline.

**Comment by rochacbruno** [comment]
To fix this we should add a layer of backwards compatibility
